version: "3"

services:
  app:
    build: .
    restart: always
    networks:
      - internal_network
      - external_network
    env_file:
      - .env

networks:
  internal_network:
    internal: true
  external_network:
